name: Release

on:
  push:
    branches: ["main"]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  packages: write

jobs:
  versioning:
    name: Update Version
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run TinySemVer
        uses: ashvardanian/tinysemver@v3
        with:
          verbose: "true"
          version-file: "VERSION"
          update-version-in: |
            Cargo.toml:^version = "(\d+\.\d+\.\d+)"
            Cargo.lock:name = "jsontape"\nversion = "(\d+\.\d+\.\d+)"
          dry-run: "false"
          push: "true"
          create-release: "true"
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Test `std`
        run: cargo test
      - name: Test `no_std`
        run: cargo test --no-default-features
      - name: Test `serde`
        run: cargo test --features serde
      - name: Test `serde` on `no_std`
        run: cargo test --no-default-features --features serde
      - name: Test docs
        run: cargo test --doc
      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Compile benches
        run: cargo bench --no-run

  fuzz:
    name: Fuzz
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Fuzz the parser
        run: |
          cargo build
          rustc --edition=2021 scripts/fuzz.rs \
            --extern jsontape=target/debug/libjsontape.rlib \
            -L dependency=target/debug/deps -o fuzz
          ./fuzz 100000 512

  publish_rust:
    name: Publish to crates.io
    runs-on: ubuntu-24.04
    needs: [versioning, test, fuzz]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: "main"
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Publish to crates.io
        uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          dry-run: false
